services:
  webdav:
    image: ionelmc/webdav
    container_name: webdav-infuse
    restart: unless-stopped
    depends_on:
      - parser
    ports:
      - "${WEBDAV_PORT}:8080"
    volumes:
      - ./strm_library:/media
    environment:
      - WEBDAV_USERNAME=${WEBDAV_USER}
      - WEBDAV_PASSWORD=${WEBDAV_PASSWORD}
      - UID=0

  torrserver:
    image: ghcr.io/yourok/torrserver:latest
    container_name: torrserver
    restart: unless-stopped
    ports:
      - "${TORR_PORT}:8090"
    volumes:
      - ./ts:/opt/ts

  parser:
    build: .
    container_name: strm-parser
    restart: unless-stopped
    depends_on:
      - torrserver
    volumes:
      - ./:/app
    environment:
      - HOST_IP=${HOST_IP}
      - TORR_PORT=${TORR_PORT}